interface=wlan0
driver=nl80211
ssid=wifi-lab
hw_mode=g
channel=6
ieee80211n=0
wmm_enabled=0

# WPA2
auth_algs=1
wpa=2
wpa_passphrase=cookie123
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP

logger_stdout=-1
logger_stdout_level=2